// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGK4OnQztO4YB39OFwEhCM_Wp645wmnXY',
    appId: '1:140622498612:web:2bc784695aa8cb667e7361',
    messagingSenderId: '140622498612',
    projectId: 'crypto-list-project',
    authDomain: 'crypto-list-project.firebaseapp.com',
    storageBucket: 'crypto-list-project.appspot.com',
    measurementId: 'G-3HBDLRMDV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEfv2WGKaL-lQE1VwsR2gCXVNklRGDqAE',
    appId: '1:140622498612:android:f4f814cca60b78cf7e7361',
    messagingSenderId: '140622498612',
    projectId: 'crypto-list-project',
    storageBucket: 'crypto-list-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeyPnNpnNWFG9oUcgEk5mNgmOgkcgtXAY',
    appId: '1:140622498612:ios:2f56257574654fd17e7361',
    messagingSenderId: '140622498612',
    projectId: 'crypto-list-project',
    storageBucket: 'crypto-list-project.appspot.com',
    iosBundleId: 'com.example.lessons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeyPnNpnNWFG9oUcgEk5mNgmOgkcgtXAY',
    appId: '1:140622498612:ios:2f56257574654fd17e7361',
    messagingSenderId: '140622498612',
    projectId: 'crypto-list-project',
    storageBucket: 'crypto-list-project.appspot.com',
    iosBundleId: 'com.example.lessons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGK4OnQztO4YB39OFwEhCM_Wp645wmnXY',
    appId: '1:140622498612:web:808f276e1853085b7e7361',
    messagingSenderId: '140622498612',
    projectId: 'crypto-list-project',
    authDomain: 'crypto-list-project.firebaseapp.com',
    storageBucket: 'crypto-list-project.appspot.com',
    measurementId: 'G-6PY1NNLZF2',
  );
}
